export default {
    PRIMARY_COLOR: "#f4511e",
    PRIMARY_LIGHT_COLOR: "#F06B43",
    SECONDARY_COLOR: "#FFF7E8",
    BACKGROUND_COLOR: "#EBEBEB",
    BACKGROUND_WHITE: "#FFFFFF",
    TEXTCOLOR_BLACK: "#000000",
    TEXTCOLOR_DARKGREY: "#808080",
    TEXTCOLOR_GREEN: "#04C424",
}